version: '3'
services:
  app:
    build:
      context: .
    tty: true
    volumes:
      - ./:/app
    command: sh -c "cd nuxt && yarn && yarn dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
